# Generated by Django 4.0.2 on 2022-03-04 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('id_prev', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_complete', models.BooleanField()),
                ('id_next', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_note', to='Notes.note')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mother_note', to='Notes.note')),
            ],
        ),
    ]
